### ISSUE TITLE
RL Transmision level autoadjust: level is lowered on transmission errors?

### ISSUE THREAD

**Issue by vanelsberg** [winemug/OmniCore#5]
Reviewing the implementation it seems to be by design, not a bug.
Only reason I can think of is RL preventing battery draining when the Pod is out of range.
But doesn't this add to communication failures due to temporary range problems?

Logic suggest a transmission level increase to regain connection to the Pod?
(This also explains why I bringing the Pod close to RL helps when trying to restoring connection)

**Comment by winemug** [comment]
@vanelsberg this is by design but your interpretation is not correct. works roughly like this:

level is raised if: pod keeps sending the same packet (because it doesn't hear the next) or no response is received

level is lowered: if received data has errors in it (this is to prevent amplification corrupting data when signal is otherwise good)

**Comment by vanelsberg** [comment]
Ah. I see ...
Missed the part on lowering specifically on _data_ response errors only.
Now it makes sense to me!
Case closed :-)
